name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: simplebank
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Passw0rd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install migrations
        run: go get -tags 'postgres' -u github.com/golang-migrate/migrate/v4/cmd/migrate/

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
